### ISSUE TITLE
Memory growing and growing

### ISSUE THREAD

**Issue by AviFix** [don/cordova-plugin-hello#8] opened 2015-06-28 07:13 UTC
HI,

I have tried to use your plugin on ios with a "setInterval" to execute every 1 sec.

Every time the " hello.greet("World", success, failure);"" is executed, the memory usage grows and grows and after about 15 minutes the app crashes with a memory error.

Thanks allot

Avi

**Comment by brodybits** [comment] 2015-06-28 10:30
Can you post the code you used and also describe where you see the objects allocated and not freed? I do not see this problem when I run a similar test in my workarea.

**Comment by Olofu** [comment] 2015-06-28 11:16
hello brodybits,
my database insert works but delete doesn't effect the changes could you please help me find out whats wrong on this 

code below


<table  cellspacing="3" border="0.5"  cellpadding="3" bordercolor="#efefef" id="loc" style="width:90%; position:relative; margin-left:auto; margin-right:auto; font-family:calibri; color:#666; font-weight:lighter;"><tr style="width:90%; font-family:calibri; color:#222; font-weight:bold; border-bottom:thin solid #efefef; text-align:left;"><td>Item</td><td>Qty</td><td>Cost</td>
<td>Selling</td>
<td>Con</td> <td>Del</td></tr>

<script type="text/javascript">
document.addEventListener("deviceready", onDeviceReady, false);
    function onDeviceReady(){
		
var ran1a3 ="UNCONFIRMED";

//var db = window.sqlitePlugin.openDatabase({name: "apro2", androidDatabaseImplementation: 2, androidLockWorkaround: 1});
var db = window.sqlitePlugin.openDatabase({name: "apro2"});

$("#but").click(function() {
var r = confirm("Do you really want to confirm all items supplied?");
	if (r==true){
		
		}
	else{
		}
	
});
      db.transaction(function(tx) {
			tx.executeSql("select proid,itemname,quantity,cprice,minsellingprice,curdate,supplyido from supply where statoso = ?", [ran1a3], function(tx, res) {
          	 var len = res.rows.length;
			// $('#location').empty();
    for (var i=0; i<len; i++){
		$('<tr style="width:90%; font-family:calibri; color:#666; font-weight:lighter; height:;  text-align:left;"><td>'+res.rows.item(i).itemname+'</td><td>'+res.rows.item(i).quantity+'</td><td>'+res.rows.item(i).cprice+'</td><td>'+res.rows.item(i).minsellingprice+'</td><td><input type="button" value="CON" style="background-color:#ccc; width:40px;box-shadow: 0px 1px 4px 0px rgba(0,0,0,0.2);border:thin solid #fff; cursor:pointer; height:20px; " id="ab'+res.rows.item(i).supplyido+'"></td><td><input type="button" value="DEL" style="background-color:#ccc; width:40px;box-shadow: 0px 1px 4px 0px rgba(0,0,0,0.2);border:thin solid #fff; cursor:pointer; height:20px; " id="a'+res.rows.item(i).supplyido+'"></td></tr>').appendTo('#loc');
		   }  
	},
 function(e) { alert("Could not load supply data");console.log("ERROR: " + e.message);    });
	});
	

	
	}
		//var db2 = window.sqlitePlugin.openDatabase({name: "apro2", androidDatabaseImplementation: 2, androidLockWorkaround: 1});
		//	db2.transaction(function(tx2) {
//var asra2x = "a"+res.rows.item(i).proid+res.rows.item(i).curdate.substring(16,25);
			//alert(asra2x);
			//$("#a"+res.rows.item(i).proid+res.rows.item(i).curdate.substring(16,25)).click(function() { 
			

</script>

</table>


<script type="text/javascript">
document.addEventListener("deviceready", onDeviceReady2, false);
    function onDeviceReady2(){
		
var ran1a3z ="UNCONFIRMED";
var ran1a3zx ="CONFIRMED";
//var db2 = window.sqlitePlugin.openDatabase({name: "apro2", androidDatabaseImplementation: 2, androidLockWorkaround: 1});
//var db3 = window.sqlitePlugin.openDatabase({name: "apro2", androidDatabaseImplementation: 2, androidLockWorkaround: 1});
var db2 = window.sqlitePlugin.openDatabase({name: "apro2"});

	db2.transaction(function(txv) {

			txv.executeSql("select supplyido from supply where statoso = ?", [ran1a3z], function(txv, res) {
          	 var len = res.rows.length;
			var asra2xcz = Array();
			alert(res.rows.length);
			for (var i=0; i<len; i++){
			
			asra2xcz[i] = res.rows.item(i).supplyido;
						
			$("#a"+res.rows.item(i).supplyido).click(function() { 
			var at = this.id.substring(1,10);
			var at = '"'+at+'"';
var r = confirm("Do you really want to delete this item?");
	if (r==true){
		db2.transaction(function(txvv) {
	alert(at);
	
	txvv.executeSql("DELETE FROM  supply where supplyido = ? ", ["bk752a0e2"], function(txvv, res) {
  // console.log("insertId: " + res.insertId + " -- probably 1");
   alert("" + res.rowsAffected + " your item was deleted"); 
     // console.log("rowsAffected: " + res.rowsAffected + " -- should be 1");
	
	}
	, function(e) {  console.log("ERROR: " + e.message);    });
	
		//txvv.executeSql("UPDATE procart set itemname = ? where itemname = ? ", ["Purple Lace","Blue Lace"], function(txvv, res) { 
		 
// alert(res.rowsAffected +" Entry Deleted"); },function(e) {alert("Heywire! an error has occured"); 		});	
		
				}, function(e) {  alert("Could not delete this item"); console.log("ERROR: " + e.message);     });

	}
	else{ alert("Delete Canceled"); } 
	});
			
			
			$("#ab"+res.rows.item(i).supplyido).click(function() { 
			var ats = this.id.substring(2,10);
			//var ats = '"'+ats+'"';
 var r = confirm("Do you really want to confirm this item?");
	if (r==true){	
	db2.transaction(function(txvva) {
	alert(ats);
		
	txvva.executeSql("UPDATE supply set statoso = ? where supplyido = ? ", ["CONFIRMED",ats], function(txvva, res) {
  alert(res.rowsAffected +" Entry Confirmed"); },function(e) {alert("Heywire! an error has occured"); 		});	
  
	//txvv.executeSql("Update procart set quantity = quantity + ? where proid = ? ", [at], function(txvv, res) { 
	 
  //alert(res.rowsAffected +" Entry Deleted"); },function(e) {alert("Heywire! an error has occured"); 		});	
		
				}, function(e) {  alert("Could not delete this item"); console.log("ERROR: " + e.message);     });
	}
	else{	alert("Couldnt Confirm"); 	} 	});
			
			}
			
			//if(i > len){ i = 0;}
		  
			
			},
 function(e) { 
 alert("Could not load supply data"); console.log("ERROR: " + e.message);    
 });
 
 });
 
	}
	</script>

**Comment by Olofu** [comment] 2015-06-28 11:20
pls include the javascript opening and closing tags for a better view thanks

**Comment by AviFix** [comment] 2015-06-28 11:24
Hi,

This is the js code:

setInterval(function(){
                    hello.greet("World", success, failure);
                    }, 100);

And this is the memory after 2 min:

![Image of Yaktocat](http://s2.postimg.org/p0191bx2x/Screen_Shot_5775_10_11_at_14_22_51.png)

**Comment by Olofu** [comment] 2015-06-28 11:25
sorry any help will be really appreciated i am testing this on android 4.4.4 Samsung

**Comment by brodybits** [comment] 2015-06-28 11:57
@Olofu I cannot help you for the following reasons:
- you have a question about the sqlite plugin, but this is a bug report for cordova-plugin-hello
- the way your code is formatted, I cannot follow it at all
- it looks like your code is part of another program

The one hint I can give you here is to open the database using window.openDatabase() and try to debug your own code. If you can isolate a self-contained test program and see something wrong with the sqlite plugin, please raise a new issue at: https://github.com/litehelpers/Cordova-sqlite-storage/issues

**Comment by brodybits** [comment] 2015-06-28 12:33
@AviFix please try to use the Instruments tool to analyze your memory usage. (I am not the author and the author has not been responsive within the past 5 months.)  I suspect you issue _could_ be within the Cordova framework itself.

**Comment by Olofu** [comment] 2015-06-29 13:55
@brodybits Thanks, i got it fixed, thanks

**Closed** 2015-07-15 21:11 UTC
